# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

# https://gitlab.com/mattia.basaglia/glaxnimate/-/ci/lint
# default:
#     before_script:
#         - apt-get update -qq
#         - apt-get install -y cmake qtbase5-dev libpython3-dev python3-pip zlib1g-dev qttools5-dev-tools qttools5-dev libpotrace-dev libavformat-dev libswscale-dev libavcodec-dev libavutil-dev libarchive-dev libqt5svg5-dev

variables:
    # DEBIAN_FRONTEND: noninteractive
    GIT_SUBMODULE_STRATEGY: recursive

reuse:
    # Overwrite reuse script step to NOT delete po/ dir (its covered in our REUSE.toml)
    script:
        - reuse lint

include:
    # - .gitlab/ci/documentation.yml
    - .gitlab/ci/python_package.yml
    # - .gitlab/ci/snap.yml
    # - .gitlab/ci/archlinux_packages.yml
    # - .gitlab/ci/deb_packages.yml
    # - .gitlab/ci/tarball.yml
    # - .gitlab/ci/release.yml
    # - .gitlab/ci/test-files.yml
    - .gitlab/ci/renderer-lib.yml
    - project: sysadmin/ci-utilities
      file:
        - /gitlab-templates/reuse-lint.yml
        # CI Qt5
        - /gitlab-templates/linux.yml
        # CI Qt6
        - /gitlab-templates/freebsd-qt6.yml
        - /gitlab-templates/linux-qt6.yml
        - /gitlab-templates/windows-qt6.yml
        - /gitlab-templates/android-qt6.yml
        # CD Qt6
        - /gitlab-templates/flatpak.yml
        - /gitlab-templates/craft-android-qt6-apks.yml
        - /gitlab-templates/craft-appimage-qt6.yml
        - /gitlab-templates/craft-windows-x86-64-qt6.yml
        - /gitlab-templates/craft-windows-appx-qt6.yml
        - /gitlab-templates/craft-macos-x86-64-qt6.yml
        - /gitlab-templates/craft-macos-arm64-qt6.yml
